### ISSUE TITLE
angular

### ISSUE THREAD

**Issue by petop2** [AimeeKnight/ama#10]
hi which text editor you use for working with angularjs?

**Comment by AimeeKnight** [comment]
Hi @petop2! I actually use Vim most of the time. Occasionally I'll use WebStorm if I'm moving things around a bunch or doing a ton of refactoring. :smiley:

**Comment by petop2** [comment]
can u give telegram id or insta for occasional questions? do u have the time or temper to answer(honestly)?

**Comment by AimeeKnight** [comment]
@petop2 Would you be willing to post here so we can share questions and answers with others who may be interested?

**Comment by petop2** [comment]
that would  do.
but some questions need a little bit of talking.
!!!!!my major question: i want to track my variables data like in visual studio in angular js.
when i wrote something it just doesn't work and i want to check if the variable had or has the value(the problem: my variables are in two file a js and html one) i need a way to track them from begining in js to end in html and it is possible there are a loop

**Comment by AimeeKnight** [comment]
@petop2 I'm not sure I understand your problem. Maybe you could create a Plunker? I'm not really familiar with vs code unfortunately either.

**Comment by petop2** [comment]
thx
