### ISSUE TITLE
Outsourcing - effects on jobs

### ISSUE THREAD

**Issue by sbchin** [AimeeKnight/ama#15]
Just started listening to Javascript Jabber - great podcast.  I only have 200+ podcasts to catch up.  I listened to podcast #180 and it brought this question to mind.

How does offshoring affect developers getting jobs in the US?  Is programming a dead end career in the US due to outsourcing?

I am an IT manager in a major financial firm and we outsource 80% of our programming jobs.

Thank you

**Comment by AimeeKnight** [comment]
@sbchin lol! Glad you like it! I don't feel it's a big concern here. From what I've heard, the improvement in team communication more than makes up for the potentially lower pay rate. Hope that helps!
