### ISSUE TITLE
React Ecosystem

### ISSUE THREAD

**Issue by aaronWcurtis** [AimeeKnight/ama#17]
I've learned JavaScript fundamentals and I'm now beginning to build apps with React. What I'm curious to know is, what does a complete React application entail? So far, what I understand is that

React - Manages the View Layer
Redux - Manages state for the application
Manage Server-Side Data - ???

So my big question is: How are companies that use React/Redux handling data on the back-end? 

I've been recommended learning how to integrate React/Redux apps with the Meteor (which I believe uses a MongoDB). So I'm leaning towards learning how to integrate my react/redux apps with Meteor AFTER I feel more comfortable with React and Redux. But I'm just curious to see what is happening in the real world.

**Comment by AimeeKnight** [comment]
Hey @aaronWcurtis! I'm so sorry for the delayed response. I'd highly recommend checking out http://teropa.info/blog/2015/09/10/full-stack-redux-tutorial.html. I haven't used Meteor, but I've definitely heard a lot about it. All of my experience has been with Express and I definitely feel like that is the most prevalent back end framework. Hope this helps! Let me know if you have any more questions, or if I should expand!
