### ISSUE TITLE
switch stements

### ISSUE THREAD

**Issue by aaronendsley** [AimeeKnight/ama#18]
I have heard many sides to this story, mostly from non JavaScript developers especially those coming from a c# background. Are case statements in JavaScript bad to use, why or why not?

**Comment by AimeeKnight** [comment]
@VeritasX So sorry for the delayed response! I'm going to have to go with the age old 'it depends' answer. I have used them on occasion, and I've seen them used on occasion. I'd recommend checking out this post: http://elijahmanor.com/javascript-smells/. Hope that helps!
