### ISSUE TITLE
Ask for feedback

### ISSUE THREAD

**Issue by anirudh-modi** [AimeeKnight/ama#19]
Hello Aimee,
Is it advisable or a good habit to ask form an interviewer about the feedback on how a technical interview went? 
Thanks,
Anirudh Modi

**Comment by AimeeKnight** [comment]
@anirudh-modi Definitely! 😃 If they don't have time immediately after the interview that's understandable though, you can shoot them an email that evening or the next day when you thank them for their time.

**Comment by anirudh-modi** [comment]
Thanks @AimeeKnight for the response and time!! 😃

**Comment by AimeeKnight** [comment]
Of course! I apologize for the delay. I've had some urgent family issues.

**Comment by anirudh-modi** [comment]
I totally understood it! No problem. 😊
