### ISSUE TITLE
Good Mentors

### ISSUE THREAD

**Issue by aaronendsley** [AimeeKnight/ama#20]
What are the qualities to look for in a mentor, especially if the only programmers you know are ones who are not specifically JavaScript developers, and dont necessarily know the trends or new frameworks of the JS community ?

**Comment by AimeeKnight** [comment]
Hi @VeritasX! I definitely think that any mentor is valuable. My mentor doesn't do very much JavaScript, but it's still immensely valuable. I would just look for someone who has a wealth of experience, and the passion and communication skills to share it. There are far too many things to learn that transcend JavaScript. One idea I think is excellent, is to pick something you both want to learn and do that together. Programming is largely about your ability to learn new things, so why not see how someone with a lot of experience goes about learning something new?! Hope this helps!
