### ISSUE TITLE
How to "Level Up"?

### ISSUE THREAD

**Issue by cgrinaldi** [AimeeKnight/ama#3]
In your podcast, you kept mentioning this idea of "leveling up". As a recent graduate of a programming bootcamp, it is also something I am really interested in. But with all of millions of things to possibly learn, and all the ways you could go about learning them, how do you even decide where to focus your efforts?

Thanks for having this AMA, and I really enjoy Javascript Jabber!

**Comment by AimeeKnight** [comment]
Hi @cgrinaldi! Yea, there definitely are a million and one things to learn right now! For me, I try to keep an overall focus on improving my speed, and ability to break down a problem. Not so much the in's and out's of a language or framework, but on how to build software. To get better with that, I'd look for way's to contribute to some large projects. Going from small apps in bootcamp, to an architecture with dozen's of API's, ETL's, a webUI, etc. has been great for me! As far as technologies, I'd say stick to one thing and learn it really well, try not to jump around too much until you really feel confident with one thing. Hope that helps, and I'm super glad you enjoyed JavaScript Jabber!
