### ISSUE TITLE
Do you wear a pair of shoes while working on a standing table?

### ISSUE THREAD

**Issue by armno** [AimeeKnight/ama#6]
Hi Aimee!

Learned from a JS Jabber episode that you also like working on a standing table. 

I'm in Thailand where we normally don't wear shoes indoor, just bare feet (or just with a pair of socks!)
I started working with a standing table a couple weeks ago but I found myself already have some pain on my rear feet when standing for 4-6 hours a day.

Do you wear a pair of shoes/slippers that support your feet when working on a standing table? 
so you don't get too much pain on your feet.

Cheers :dancers: ,
Armno

**Comment by AimeeKnight** [comment]
I actually don't wear shoes either indoors. I do however have a fatigue mat that I stand on which really helps. I also like to move around every hour or so to go get a drink so that I keep my circulation going! Hopefully that helps! 👣

**Comment by armno** [comment]
awesome :sparkles: 
thanks @AimeeKnight
