### ISSUE TITLE
Baltimore JS Community 

### ISSUE THREAD

**Issue by cukejianya** [AimeeKnight/ama#7]
I was listening to the 'Finding a Job' on JSJ and heard you currently live in the Baltimore Area. I know about several js communities in the DC area but not a lot in Baltimore. Can you share ones that you were/are involved in? I would love to get more involved and I truly believe the best way for me to level up my coding skills is to become more active within the JS community.  

Also, great podcast episode on JSJ.

**Comment by AimeeKnight** [comment]
Hi @cukejianya! You're right, Baltimore's been pretty quiet, but we (folks at CharmCityJS) are trying to help! I'd definitely check out @CharmCityJS... I just spoke there Wednesday actually. You can also try to make it out to http://www.meetup.com/Maryland-Javascript-Meetup/. I may be speaking there the 18th as well. Hope that helps!
