### ISSUE TITLE
Mentor/mentee discussions

### ISSUE THREAD

**Issue by BSVino** [AimeeKnight/ama#8]
Your Nodevember talk stressed the importance of mentorship. What are your suggestions for what a mentor can discuss with their mentee during their time together?

**Comment by AimeeKnight** [comment]
Hi @BSVino! I'd recommend the mentee come prepared with a list of things they want to cover each week. (Even better if you can send your mentor the list of question ahead of time so they can prepare if needed.) You can also review your mentee's code, and offer feedback on how you'd solve the problem, and pair program together (bonus for TDD), on small challenges. Honestly, I don't think it matters. Any of these things are valuable! Hope that helps!
