### ISSUE TITLE
CS self-teaching curriculum?

### ISSUE THREAD

**Issue by scunningham777** [AimeeKnight/ama#9]
I'm a long-time listener of Javascript Jabber, and as a self-taught web developer I'm always inspired by your story of breaking into the industry and learning so much so quickly. I listened to the episode on NativeScript recently, where you mentioned at the end of the episode that you are trying to take a break from learning specific frameworks and libraries, and trying to focus more on learning fundamental CS concepts. This is something I've felt a need for for a while as well, but I really feel like I don't even know what I don't know. Do you have a curriculum that you are working off of, or a list of topics that you want to learn or anything?

Keep up the great work and thanks a ton for any help you can give!

**Comment by AimeeKnight** [comment]
Hi @scunningham777! I do! Here's what I've been looking at lately.
- https://www.youtube.com/user/UNSWelearning/playlists?shelf_id=6&view=50&sort=dd
- https://www.interviewcake.com/
- https://www.khanacademy.org/computing/computer-science

I've especially enjoyed the first link from UNSW elearning! Let me know what you think!

**Comment by scunningham777** [comment]
Great, thanks!

There's definitely enough material in here to last quite a while! I definitely like to blend in multiple mediums/platforms when I'm learning something new, so these will definitely come in handy.

I guess partly what I'm looking for is some comprehensive "checklist" of things you need to know in order to be considered competent in CS. Kind of like a CompTIA Network+ certification or something, where some third party organization puts together a list of all the subjects you need to know. Are you aware of any such lists from authoritative sources? 

Thanks again!

**Comment by AimeeKnight** [comment]
@scunningham777 ah, yes, that is unfortunately something I haven't seen. If you do find something, definitely let me know, and I'll do the same. :)
